Dataset - https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Завдання:


1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)
2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
3. Порахувати mean, median, standard deviation для 1-ї колонки
4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)
5. Знайти позиції вставлених значень np.nan в 1-й колонці
6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)
7. Замінити всі значення np.nan на 0
8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю
9. Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)
10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням
11. Зібрати обидва массиви в одне ціле
12. Знайти найбільш часто повторюване значення в массиві
13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.
14. Застосувати отриману функцію до 3-ї колонки

In [31]:
# Mount GD with a dataset. Use code below if you want to load dataset from your Goodle Drive
# from google.colab import drive
# drive.mount("/content/drive")

In [32]:
# Import numpy
import numpy as np

In [33]:
# Load dataset
# uncomment code below if you want to load dataset from mounted Goodle Drive directory
# data = np.loadtxt("/content/drive/MyDrive/Hillel ML 09.06.2023/datasets/archive.ics.uci.edu_ml_machine-learning-databases_iris_iris.data.txt", delimiter=",", dtype="str")
# data  # uncomment this variable if you want to check entire dataset
data = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", dtype=str, delimiter=",")

In [34]:
# Let's check dataset parameters
print("Shape: ", data.shape)
print("Datatype: ", data.dtype)
print("Size: ", data.size)
print("Dimensions: ", data.ndim)

Shape:  (150, 5)
Datatype:  <U15
Size:  750
Dimensions:  2


In [35]:
# Task 1 - delete a column with a target
# delete method returns a new array, so let's store it into a new variable `cleared_data`
cleared_data = np.delete(data, 4, axis=1)
# cleared_data  # uncomment this variable if you want to check entire dataset
# check the shape and size of the cleaned dataset
print("Shape: ", cleared_data.shape)
print("Size: ", cleared_data.size)

Shape:  (150, 4)
Size:  600


In [36]:
# Task 2 - Transform columns that are left in a 2D array (or check, if it’s still a 2D array)
print("Dimensions: ", cleared_data.ndim)
# Yep, we are still in 2D array, because we were using np.delete for removing last column. Otherwise, dataset should be reshaped.

Dimensions:  2


In [37]:
# Task 3 - Calculate mean, median and standard deviation for the 1-st column
# First of all let's convert dataset to a float data
cleared_data = cleared_data.astype("float32")
first_column_data = cleared_data[:, 0]
print("Mean: ", np.mean(first_column_data))
print("Median: ", np.median(first_column_data))
print("Standard deviation: ", np.std(first_column_data))

Mean:  5.8433332
Median:  5.8
Standard deviation:  0.8253013


In [38]:
# Task 4 - Insert 20 np.nan on a random positions in the array
np.random.seed(100)
indices = np.random.choice(range(cleared_data.size), size=20, replace=False)  # get 20 unique positions
print(indices)

original_shape = cleared_data.shape  # store original array shape here
cleared_data.ravel()  # we don't need a copy here, so let's use reveal() instaed of flatten()

np.put(cleared_data, indices, np.nan)  # replace values by indices
print(np.take(cleared_data, indices))  # let's re-check if all indices were replaced correctly

# and, finally, let's reshape data to the original shape
np.reshape(cleared_data, original_shape)
print("Dimensions: ", cleared_data.ndim)

[360 239 365 306 575 424 270 173  48  75 498 125 554 418 149 106 142 257
 118 359]
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]
Dimensions:  2


In [39]:
# Task 5 - Find positions of inserted NaN values in the 1st column
indeces = np.argwhere(np.isnan(cleared_data[:, 0]))
print(indeces)

# recheck if we found the indices correctly
print(cleared_data[:, 0][12])
print(cleared_data[:, 0][90])
print(cleared_data[:, 0][106])

[[ 12]
 [ 90]
 [106]]
nan
nan
nan


In [40]:
# Task 6 - Filter array by conditions: values in 3rd column > 1.5 and values in the 1st column < 5.0 (save into a new variable)
mask = np.logical_and(cleared_data[:, 2] > 1.5, cleared_data[:, 0] < 5.0)
filtered_data = cleared_data[mask]
filtered_data

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ]], dtype=float32)

In [41]:
# Task 7 - Replace all np.nan with 0
# There is, at least, 2 ways to do that
# Option 1 - use basic syntax + np.isnan
a = np.copy(cleared_data)
a[np.isnan(a)] = 0
# print(a)
# Option 2 - use np.nun_to_num(0)
np.nan_to_num(cleared_data, copy=False, nan=0)
print(cleared_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0. ]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 0.  0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 0.  1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 0.  0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 0.  1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  0.  1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [42]:
# Task 8 - Count all unique values in the array and output them together with their quantity
values, counts = np.unique(cleared_data, return_counts=True)
print("Values : ", values)
print("Counts : ", counts)

Values :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Counts :  [20  6 28  6  7  1  1  8  4  6 19 19 26  9  6 12  7  7  6  6 11  6 11  5
  9 14  9 26 11 13  8 11  7  4  4  7  5  6  3  5  3  8  9  7  7  6 10 14
 17  6  3  8  9 12 10  9  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1
  1  4  1]


In [43]:
# Task 9 - Split an array into multiple sub-arrays horizontally into 2 parts
# Interesting, but looks like hsplit makes vertical split, but not horizantal.
# And vsplit makes a horizontal split.
part_1, part_2 = np.vsplit(cleared_data, 2)
print(part_1.shape)
print(part_2.shape)
# or we can use np.split. Basically, vsplit it's equivalent to split with axis=0
part_1, part_2 = np.split(cleared_data, 2, axis=0)
print(part_1.shape)
print(part_2.shape)

(75, 4)
(75, 4)
(75, 4)
(75, 4)


In [44]:
# Task 10 - Sort both arrays by 1-st column: 1-st array ascending order, 2-nd by descending
# sort first array in ascending order by the first column
part_1_sorted_indeces = part_1[:, 0].argsort()
part_1 = part_1[part_1_sorted_indeces]
print(part_1_sorted_indeces)
# print(part_1)

# sort seconds array in descending order by the first column
part_2_sorted_indeces = part_2[:, 0].argsort()
part_2 = part_2[part_2_sorted_indeces[::-1] ]  # desc sorting
print(part_2_sorted_indeces)
# print(part_2)

[12 13  8 42 38 41  3  6 47 22  2 29 45 24 30 11 37 34 57  9  1 43 49 40
  7 25 26 60  4 35 44 39 46  0 17 19 21 23 59 32 28 27 48 16  5 31 20 10
 36 53 33 64 66 69 18 55 15 67 14 70 61 62 71 63 73 68 56 72 74 51 54 58
 65 52 50]
[15 31 18 23  9  5  6 14 46 19 13 24 21 20  4 38  7 17 39 67 26 74 44 10
 63  3  8 52 16 59 22 51 73 71 48 61 28 25 12 58 36 62 40 57 53 29 41 72
 35  0  2 70 69 11 33 65 49 37  1 68 45 66 64 27 50 34 54 32 55 30 60 42
 43 47 56]


In [45]:
# Task 11 - Concatenate array into one
# np.concatenate([part_1, part_2], axis=0) or
# np.r_[part_1, part_2] also can be used
final_data = np.vstack([part_1, part_2])
print(final_data)

[[0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 0.  1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  0.  1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 0.  0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 0.  0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 2.7 3.9 0. ]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 0.  1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 0.  3.6 1.3]
 [5.6 3.  4.

In [46]:
# Task 12 - Find most frequent number in array
values, counts = np.unique(final_data, return_counts=True)
print("Most frequent values is: ", values[counts.argmax()])

Most frequent values is:  0.2


In [47]:
# Task 13 - Create a function, which should multiply on 2 all values in the column,
# which are less than mean value of this column, and should divide all other values on 4
def modify(arr):
  """Modify provided array."""
  return np.where(arr < np.mean(arr), arr * 2, arr / 4)

In [48]:
# Task 14 - Apply function to the 3-rd column
final_data[:, 2] = modify(final_data[:, 2])
print(final_data)

[[0.    3.    2.8   0.1  ]
 [4.3   3.    2.2   0.1  ]
 [4.4   2.9   2.8   0.2  ]
 [4.4   3.2   2.6   0.2  ]
 [4.4   3.    2.6   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.1   3.    0.2  ]
 [4.6   3.4   2.8   0.3  ]
 [4.6   3.2   2.8   0.2  ]
 [4.6   3.6   2.    0.2  ]
 [4.7   3.2   2.6   0.2  ]
 [4.7   3.2   0.    0.2  ]
 [4.8   3.    2.8   0.3  ]
 [4.8   3.4   3.8   0.2  ]
 [4.8   3.1   3.2   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.9   0.    3.    0.1  ]
 [4.9   3.1   3.    0.1  ]
 [4.9   2.4   6.6   1.   ]
 [4.9   3.1   3.    0.1  ]
 [4.9   3.    2.8   0.2  ]
 [5.    0.    3.2   0.6  ]
 [5.    3.3   2.8   0.2  ]
 [5.    3.5   2.6   0.3  ]
 [5.    3.4   3.    0.2  ]
 [5.    3.    3.2   0.2  ]
 [5.    3.4   0.    0.4  ]
 [5.    2.    7.    1.   ]
 [5.    3.6   2.8   0.2  ]
 [5.    3.2   0.    0.2  ]
 [5.1   3.8   3.8   0.4  ]
 [5.1   3.4   3.    0.2  ]
 [5.1   3.8   3.2   0.2  ]
 [5.1   3.5   2.8   0.2  ]
 [5.1   3.5   2.8   0.3  ]
 [5.1   3.8   3.    0.3  ]
 [5.1   3.7   3.    0.4  ]
 

In [49]:
# Additional tasks

In [50]:
# Count non-zero values
print("Total values: ", final_data.size)
print("Non-zero values: ", np.count_nonzero(final_data))

Total values:  600
Non-zero values:  580


In [51]:
# Extract all values that are less than 1
result = np.extract(final_data < 1, final_data)
print(result)

[0.    0.1   0.1   0.2   0.2   0.2   0.3   0.2   0.3   0.2   0.2   0.2
 0.    0.2   0.3   0.2   0.2   0.2   0.    0.1   0.1   0.1   0.2   0.
 0.6   0.2   0.3   0.2   0.2   0.    0.4   0.2   0.    0.2   0.4   0.2
 0.2   0.2   0.3   0.3   0.4   0.5   0.975 0.    0.1   0.2   0.2   0.2
 0.4   0.4   0.    0.4   0.2   0.2   0.2   0.2   0.    0.9   0.975 0.
 0.4   0.    0.2   0.    0.    0.    0.    0.    0.    0.975 0.    0.925
 0.95  0.    0.   ]


In [52]:
# Create array of dates with 2-hours step in a range from 15 June till 25 June
dates = np.arange("2023-06-15T08:00", "2023-06-25T08:00", 120, dtype="M8[m]")
dates

array(['2023-06-15T08:00', '2023-06-15T10:00', '2023-06-15T12:00',
       '2023-06-15T14:00', '2023-06-15T16:00', '2023-06-15T18:00',
       '2023-06-15T20:00', '2023-06-15T22:00', '2023-06-16T00:00',
       '2023-06-16T02:00', '2023-06-16T04:00', '2023-06-16T06:00',
       '2023-06-16T08:00', '2023-06-16T10:00', '2023-06-16T12:00',
       '2023-06-16T14:00', '2023-06-16T16:00', '2023-06-16T18:00',
       '2023-06-16T20:00', '2023-06-16T22:00', '2023-06-17T00:00',
       '2023-06-17T02:00', '2023-06-17T04:00', '2023-06-17T06:00',
       '2023-06-17T08:00', '2023-06-17T10:00', '2023-06-17T12:00',
       '2023-06-17T14:00', '2023-06-17T16:00', '2023-06-17T18:00',
       '2023-06-17T20:00', '2023-06-17T22:00', '2023-06-18T00:00',
       '2023-06-18T02:00', '2023-06-18T04:00', '2023-06-18T06:00',
       '2023-06-18T08:00', '2023-06-18T10:00', '2023-06-18T12:00',
       '2023-06-18T14:00', '2023-06-18T16:00', '2023-06-18T18:00',
       '2023-06-18T20:00', '2023-06-18T22:00', '2023-06-19T00:

In [53]:
# Convert array of dates to the array of strings with seconds and Kyiv timezone
import pytz
dates_s = np.datetime_as_string(dates, unit="s", timezone=pytz.timezone("Europe/Kyiv"))
dates_s

array(['2023-06-15T11:00:00+0300', '2023-06-15T13:00:00+0300',
       '2023-06-15T15:00:00+0300', '2023-06-15T17:00:00+0300',
       '2023-06-15T19:00:00+0300', '2023-06-15T21:00:00+0300',
       '2023-06-15T23:00:00+0300', '2023-06-16T01:00:00+0300',
       '2023-06-16T03:00:00+0300', '2023-06-16T05:00:00+0300',
       '2023-06-16T07:00:00+0300', '2023-06-16T09:00:00+0300',
       '2023-06-16T11:00:00+0300', '2023-06-16T13:00:00+0300',
       '2023-06-16T15:00:00+0300', '2023-06-16T17:00:00+0300',
       '2023-06-16T19:00:00+0300', '2023-06-16T21:00:00+0300',
       '2023-06-16T23:00:00+0300', '2023-06-17T01:00:00+0300',
       '2023-06-17T03:00:00+0300', '2023-06-17T05:00:00+0300',
       '2023-06-17T07:00:00+0300', '2023-06-17T09:00:00+0300',
       '2023-06-17T11:00:00+0300', '2023-06-17T13:00:00+0300',
       '2023-06-17T15:00:00+0300', '2023-06-17T17:00:00+0300',
       '2023-06-17T19:00:00+0300', '2023-06-17T21:00:00+0300',
       '2023-06-17T23:00:00+0300', '2023-06-18T01:00:00

In [54]:
# check what dates are working days in the provided array
dates_days = np.unique(dates.astype("M8[D]"))
print(dates_days)
np.is_busday(dates_days, holidays=["2023-06-17", "2023-06-18", "2023-06-24", "2023-06-25"])

['2023-06-15' '2023-06-16' '2023-06-17' '2023-06-18' '2023-06-19'
 '2023-06-20' '2023-06-21' '2023-06-22' '2023-06-23' '2023-06-24'
 '2023-06-25']


array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False, False])

In [55]:
# Get second Sunday in July
np.busday_offset("2023-07", 1, roll="forward", weekmask="Sun")

numpy.datetime64('2023-07-09')

In [56]:
# Calculate Fridays in June
np.busday_count("2023-06", "2023-07", weekmask="Fri")

5